// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUser struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	IsActive bool   `json:"isActive"`
}

type User struct {
	ID        string `json:"id" bson:"id"`
	Name      string `json:"name" bson:"name"`
	CreatedOn int    `json:"createdOn" bson:"createdOn"`
	UpdatedOn int    `json:"updatedOn" bson:"updatedOn"`
	Deleted   bool   `json:"deleted" bson:"deleted"`
	IsActive  bool   `json:"isActive" bson:"isActive"`
}
